I don't know why this is here. Let's find out.
This makes py3 complain with native str paths.

E.g.

[ERROR]
Traceback (most recent call last):
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/twisted/trial/runner.py, line 508, in loadPackage
    module = modinfo.load()
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/twisted/python/modules.py, line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/twisted/python/reflect.py, line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/twisted/python/reflect.py, line 247, in _importAndCheckStack
    return __import__(importName)
  File /Users/Julian/Development/jsonschema/jsonschema/tests/test_jsonschema_test_suite.py, line 25, in <module>
    DRAFT3 = SUITE.collection(name=draft3)
  File /Users/Julian/Development/jsonschema/jsonschema/tests/_suite.py, line 61, in collection
    path=self._root.descendant([tests, name]),
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/bp/generic.py, line 108, in genericDescendant
    path = path.child(name)
  File /Users/Julian/Development/jsonschema/.tox/py36-tests/lib/python3.6/site-packages/bp/filepath.py, line 289, in child
    if self.sep in path:
builtins.TypeError: 'in <string>' requires string as left operand, not bytes

jsonschema.tests.test_jsonschema_test_suite